{
    "Dashboard": "Kojelauta",
    "Staff": "Henkilökunta",
    "Manager": "Johtaja",
    "Admin": "Ylläpitäjä",
    "Account Settings": "Tilin asetukset",
    "Sign Out": "Kirjaudu ulos",
    "Home": "Koti",
    "Account": "Tili",
    "Security": "Turvallisuus",
    "API Credentials": "API-tunnistetiedot",
    "SSH Keys": "SSH-avaimet",
    "API": "API",
    "SSH": "SSH",
    "Activity": "Toiminta",
    "Logout": "Kirjaudu ulos",
    "Portal": "Portaali",
    "Premium Server": "Premium-palvelin",
    "Free Server": "Ilmainen palvelin",
    "Tutorials": "Opetusohjelmat",
    "Discord": "Discord",
    "Server": "Palvelin",
    "Console": "Konsoli",
    "Files": "Tiedostot",
    "Showing your servers": "Näytetään palvelimesi",
    "Showing others' servers": "Näytetään muiden palvelimia",
    "You are a premium user! To redeem your customer role and access premium support, join our Discord and create a ticket.": "Olet premium-käyttäjä! Lunastaaksesi asiakasroolisi ja päästäksesi premium-tukeen, liity Discordiimme ja luo tiketti.",
    "Create Free Server": "Luo ilmainen palvelin",
    "No servers found.": "Palvelimia ei löytynyt.",
    "It looks like you have no servers.": "Näyttää siltä, että sinulla ei ole palvelimia.",
    "All Rights Reserved.": "Kaikki oikeudet pidätetään.",
    "Terms of Service": "Käyttöehdot",
    "Privacy Policy": "Tietosuojakäytäntö",
    "Create": "Luo",
    "Save": "Tallenna",
    "Cancel": "Peruuta",
    "Delete": "Poista",
    "Edit": "Muokkaa",
    "Update": "Päivitä",
    "Back": "Takaisin",
    "Close": "Sulje",
    "Confirm": "Vahvista",
    "Yes": "Kyllä",
    "No": "Ei",
    "Submit": "Lähetä",
    "View Details": "Näytä tiedot",
    "Search": "Hae",
    "Filter": "Suodatin",
    "Import": "Tuo",
    "Export": "Vie",
    "Download": "Lataa",
    "Upload": "Lataa palvelimelle",
    "Connect": "Yhdistä",
    "Disconnect": "Katkaise yhteys",
    "Copy": "Kopioi",
    "Refresh": "Päivitä",
    "Apply": "Käytä",
    "Return to Login": "Palaa kirjautumiseen",
    "Install": "Asenna",
    "Uninstall": "Poista",
    "Reinstall": "Asenna uudelleen",
    "Configure": "Määritä",
    "View": "Näytä",
    "Start": "Käynnistä",
    "Stop": "Pysäytä",
    "Restart": "Käynnistä uudelleen",
    "Kill": "Lopeta",
    "Send": "Lähetä",
    "Continue": "Jatka",
    "Next": "Seuraava",
    "Previous": "Edellinen",
    "Finish": "Viimeistele",
    "Reset": "Nollaa",
    "Clear": "Tyhjennä",
    "Select": "Valitse",
    "Deselect": "Poista valinta",
    "Enable": "Ota käyttöön",
    "Disable": "Poista käytöstä",
    "Active": "Aktiivinen",
    "Inactive": "Epäaktiivinen",
    "Pending": "Odottaa",
    "Completed": "Valmis",
    "Failed": "Epäonnistui",
    "Loading": "Ladataan",
    "Loading...": "Ladataan...",
    "Success": "Onnistui",
    "Error": "Virhe",
    "Warning": "Varoitus",
    "Info": "Tiedot",
    "Online": "Online",
    "Offline": "Offline",
    "Starting": "Käynnistyy",
    "Stopping": "Pysähtyy",
    "Running": "Käynnissä",
    "Suspended": "Keskeytetty",
    "Installing": "Asentaa",
    "Restoring": "Palauttaa",
    "Transferring": "Siirtää",
    "Successfully saved.": "Tallennus onnistui.",
    "Successfully updated.": "Päivitys onnistui.",
    "Successfully deleted.": "Poisto onnistui.",
    "Successfully created.": "Luonti onnistui.",
    "Are you sure you want to delete this?": "Haluatko varmasti poistaa tämän?",
    "This action cannot be undone.": "Tätä toimintoa ei voi kumota.",
    "No results found.": "Tuloksia ei löytynyt.",
    "No servers found matching your search.": "Hakutuloksiisi sopivia palvelimia ei löytynyt.",
    "Searching...": "Haetaan...",
    "Copied to clipboard": "Kopioitu leikepöydälle",
    "Click to copy": "Kopioi napsauttamalla",
    "Click to copy allocation(s)": "Kopioi allokaatiot napsauttamalla",
    "Something went wrong.": "Jotain meni pieleen.",
    "An error occurred.": "Tapahtui virhe.",
    "Please try again later.": "Yritä myöhemmin uudelleen.",
    "Access Denied": "Pääsy evätty",
    "You do not have permission to access this page.": "Sinulla ei ole oikeutta käyttää tätä sivua.",
    "Page not found": "Sivua ei löytynyt",
    "The page you are looking for does not exist.": "Etsimääsi sivua ei ole olemassa.",
    "Name": "Nimi",
    "Description": "Kuvaus",
    "Email": "Sähköposti",
    "Password": "Salasana",
    "Current Password": "Nykyinen salasana",
    "New Password": "Uusi salasana",
    "Confirm Password": "Vahvista salasana",
    "Confirm New Password": "Vahvista uusi salasana",
    "Username": "Käyttäjänimi",
    "Type to search...": "Kirjoita hakeaksesi...",
    "Search...": "Hae...",
    "Notes": "Muistiinpanot",
    "Reason": "Syy",
    "Value": "Arvo",
    "Key": "Avain",
    "Variable": "Muuttuja",
    "Port": "Portti",
    "IP Address": "IP-osoite",
    "Host": "Isäntä",
    "Database": "Tietokanta",
    "Databases": "Tietokannat",
    "This field is required": "Tämä kenttä on pakollinen",
    "Please enter a valid email address": "Syötä voimassa oleva sähköpostiosoite",
    "Passwords do not match": "Salasanat eivät täsmää",
    "Password must be at least 8 characters": "Salasanan on oltava vähintään 8 merkkiä",
    "Optional": "Valinnainen",
    "Required": "Pakollinen",
    "File Manager": "Tiedostohallinta",
    "Server Info": "Palvelimen tiedot",
    "Schedules": "Aikataulut",
    "Users": "Käyttäjät",
    "Backups": "Varmuuskopiot",
    "Network": "Verkko",
    "Startup": "Käynnistys",
    "Settings": "Asetukset",
    "Terminal": "Pääte",
    "Modpacks": "Modipaketit",
    "Mods": "Modit",
    "Properties": "Ominaisuudet",
    "World Manager": "Maailmanhallinta",
    "Google Drive Backup": "Google Drive -varmuuskopio",
    "Plugin manager": "Liitännäisten hallinta",
    "Minecraft Player Manager": "Minecraft-pelaajien hallinta",
    "Servers": "Palvelimet",
    "Server Name": "Palvelimen nimi",
    "Server Description": "Palvelimen kuvaus",
    "Server Status": "Palvelimen tila",
    "Server Information": "Palvelimen tiedot",
    "Server Settings": "Palvelimen asetukset",
    "SFTP Details": "SFTP-yksityiskohdat",
    "Debug Information": "Vianjäljitystiedot",
    "Reinstall Server": "Asenna palvelin uudelleen",
    "Transfer Server": "Siirrä palvelin",
    "Delete Server": "Poista palvelin",
    "Memory": "Muisti",
    "CPU": "Suoritin",
    "Disk": "Levy",
    "Disk Space": "Levytila",
    "Current Resource Usage": "Nykyinen resurssien käyttö",
    "Allocated": "Varattu",
    "Used": "Käytetty",
    "Available": "Käytettävissä",
    "New File": "Uusi tiedosto",
    "New Folder": "Uusi kansio",
    "Upload Files": "Lataa tiedostoja palvelimelle",
    "File Name": "Tiedostonimi",
    "Folder Name": "Kansion nimi",
    "Size": "Koko",
    "Last Modified": "Viimeksi muokattu",
    "Permissions": "Käyttöoikeudet",
    "Compress": "Pakkaa",
    "Decompress": "Pura",
    "Archive": "Arkisto",
    "Extract": "Pura",
    "Rename": "Nimeä uudelleen",
    "Move": "Siirrä",
    "Mass Delete": "Massapoisto",
    "Schedule": "Aikataulu",
    "New Schedule": "Uusi aikataulu",
    "Schedule Name": "Aikataulun nimi",
    "Enabled": "Käytössä",
    "Disabled": "Poissa käytöstä",
    "Last Run": "Viimeisin suoritus",
    "Next Run": "Seuraava suoritus",
    "Tasks": "Tehtävät",
    "New Task": "Uusi tehtävä",
    "Task": "Tehtävä",
    "Action": "Toiminto",
    "Actions": "Toiminnot",
    "Payload": "Hyötykuorma",
    "Time Offset": "Aikasiirros",
    "Continue on Failure": "Jatka epäonnistumisesta huolimatta",
    "Backup": "Varmuuskopio",
    "Create Backup": "Luo varmuuskopio",
    "Backup Name": "Varmuuskopion nimi",
    "Locked": "Lukittu",
    "Unlocked": "Avattu",
    "Checksum": "Tarkistesumma",
    "Restore": "Palauta",
    "Download Backup": "Lataa varmuuskopio",
    "Delete Backup": "Poista varmuuskopio",
    "Lock Backup": "Lukitse varmuuskopio",
    "Unlock Backup": "Avaa varmuuskopio",
    "User": "Käyttäjä",
    "Email Address": "Sähköpostiosoite",
    "Subusers": "Alikäyttäjät",
    "New User": "Uusi käyttäjä",
    "Invite User": "Kutsu käyttäjä",
    "Grant Permissions": "Myönnä käyttöoikeudet",
    "Revoke Permissions": "Kumoa käyttöoikeudet",
    "Select All": "Valitse kaikki",
    "Deselect All": "Poista kaikki valinnat",
    "Allocations": "Allokaatiot",
    "Primary": "Ensisijainen",
    "Make Primary": "Tee ensisijaiseksi",
    "Alias": "Alias",
    "Assign Additional Ports": "Määritä lisäportteja",
    "Startup Command": "Käynnistyskomento",
    "Startup Variables": "Käynnistysmuuttujat",
    "Docker Image": "Docker-kuva",
    "Default Value": "Oletusarvo",
    "Billing": "Laskutus",
    "Balance": "Saldo",
    "Cart": "Ostoskori",
    "My Plans": "Omat suunnitelmat",
    "Manage": "Hallinnoi",
    "Plugin": "Liitännäinen",
    "Account Balance": "Tilin saldo",
    "PayPal": "PayPal",
    "Stripe": "Stripe",
    "Gift Card": "Lahjakortti",
    "Billing Information": "Laskutustiedot",
    "Please enter the amount you would like to add": "Syötä lisättävä summa",
    "Amount": "Määrä",
    "Card Holder Name": "Kortin haltijan nimi",
    "Card Number": "Kortin numero",
    "Expiration Date": "Viimeinen käyttöpäivä",
    "CVV": "CVV",
    "Pay Now": "Maksa nyt",
    "Address": "Osoite",
    "First Name": "Etunimi",
    "Last Name": "Sukunimi",
    "City": "Kaupunki",
    "Country": "Maa",
    "State": "Osavaltio",
    "Province": "Maakunta",
    "Postal Code": "Postinumero",
    "ZIP Code": "Postinumero",
    "Phone": "Puhelin",
    "Phone Number": "Puhelinnumero",
    "Update Billing Information": "Päivitä laskutustiedot",
    "Edit Account": "Muokkaa tiliä",
    "Account API": "Tilin API",
    "Admin Area": "Ylläpitoalue",
    "Dark Mode": "Tumma tila",
    "Light Mode": "Vaalea tila",
    "Gift Card Code": "Lahjakortin koodi",
    "Redeem": "Lunasta",
    "Balance:": "Saldo:",
    "Current Balance:": "Nykyinen saldo:",
    "Checkout": "Kassa",
    "Game": "Peli",
    "Plan": "Suunnitelma",
    "Price": "Hinta",
    "Billed": "Laskutettu",
    "Cart is empty.": "Ostoskori on tyhjä.",
    "Place Order": "Tee tilaus",
    "Plan Name": "Suunnitelman nimi",
    "Total": "Yhteensä",
    "Subtotal": "Välisumma",
    "Discount": "Alennus",
    "Total Order: ": "Tilauksen yhteissumma: ",
    "After clicking \"Confirm Order\", your order will be placed and the amount will be reduced from your current balance.": "Kun napsautat \"Vahvista tilaus\", tilaus tehdään ja summa vähennetään nykyisestä saldostasi.",
    "Discount Code": "Alennuskoodi",
    "Apply Discount": "Käytä alennus",
    "Remove from Cart": "Poista ostoskorista",
    "Date": "Päivämäärä",
    "View Plans": "Näytä suunnitelmat",
    "View Invoices": "Näytä laskut",
    "Extend": "Laajenna",
    "days for": "päivää hintaan",
    "Deleted": "Poistettu",
    "Pay": "Maksa",
    "Are you sure?": "Oletko varma?",
    "Remove": "Poista",
    "Plans": "Suunnitelmat",
    "Add to Cart": "Lisää ostoskoriin",
    "Monthly": "Kuukausittain",
    "Yearly": "Vuosittain",
    "Year": "Vuosi",
    "Quarterly": "Neljännesvuosittain",
    "Weekly": "Viikottain",
    "Daily": "Päivittäin",
    "One Time": "Kertaluonteinen",
    "Unlimited": "Rajoittamaton",
    "Days": "päivää",
    "Hours": "tuntia",
    "Minutes": "minuuttia",
    "CPU:": "Suoritin:",
    "RAM:": "Keskusmuisti:",
    "Disk:": "Levy:",
    "Storage:": "Tallennustila:",
    "Backup(s)": "Varmuuskopio(t)",
    "Database(s)": "Tietokanta(t)",
    "Extra Ports": "Lisäportit",
    "Slots": "Paikat",
    "Players": "Pelaajat",
    "Invoice": "Lasku",
    "Invoices": "Laskut",
    "Invoice Date:": "Laskun päivämäärä:",
    "Due Date:": "Eräpäivä:",
    "Invoice Date": "Laskun päivämäärä",
    "Due Date": "Eräpäivä",
    "Price:": "Hinta:",
    "Status": "Tila",
    "Paid": "Maksettu",
    "Unpaid": "Maksamaton",
    "Overdue": "Myöhässä",
    "Cancelled": "Peruutettu",
    "Refunded": "Hyvitetty",
    "Renew Plan": "Uusi suunnitelma",
    "View Invoice": "Näytä lasku",
    "Request Cancellation": "Pyydä peruutusta",
    "Renew": "Uusi",
    "Plan added to cart": "Suunnitelma lisätty ostoskoriin",
    "Your server has been created successfully, go to My Plans for more information.": "Palvelimesi on luotu onnistuneesti, siirry Omat suunnitelmat saadaksesi lisätietoja.",
    "Payment successful!": "Maksu onnistui!",
    "Order placed successfully!": "Tilaus tehty onnistuneesti!",
    "Balance added successfully!": "Saldo lisätty onnistuneesti!",
    "Sorry. You must first remove all plans that belong to this game.": "Anteeksi. Sinun on poistettava ensin kaikki tähän peliin kuuluvat suunnitelmat.",
    "Sorry. You have reached a limit. You can only purchase the following amount: ": "Anteeksi. Olet saavuttanut rajan. Voit ostaa vain seuraavan määrän: ",
    "An error occurred while creating a new server.": "Uuden palvelimen luonnissa tapahtui virhe.",
    "There is not enough balance in your account to make this purchase.": "Tililläsi ei ole tarpeeksi saldoa tämän ostoksen tekemiseen.",
    "Plan has been removed from your cart.": "Suunnitelma on poistettu ostoskoristasi.",
    "There are no plans for this game.": "Tälle pelille ei ole suunnitelmia.",
    "Invalid discount code.": "Virheellinen alennuskoodi.",
    "Discount code expired.": "Alennuskoodi on vanhentunut.",
    "Payment failed.": "Maksu epäonnistui.",
    "Insufficient funds.": "Riittämättömät varat.",
    "Today": "Tänään",
    "Yesterday": "Eilen",
    "Tomorrow": "Huomenna",
    "Now": "Nyt",
    "Never": "Ei koskaan",
    "Just now": "Juuri nyt",
    "a minute ago": "minuutti sitten",
    "minutes ago": "minuuttia sitten",
    "an hour ago": "tunti sitten",
    "hours ago": "tuntia sitten",
    "a day ago": "päivä sitten",
    "days ago": "päivää sitten",
    "a week ago": "viikko sitten",
    "weeks ago": "viikkoa sitten",
    "a month ago": "kuukausi sitten",
    "months ago": "kuukautta sitten",
    "a year ago": "vuosi sitten",
    "years ago": "vuotta sitten",
    "Page": "Sivu",
    "of": "/",
    "Showing": "Näytetään",
    "to": "-",
    "entries": "merkintää",
    "results": "tulosta",
    "First": "Ensimmäinen",
    "Last": "Viimeinen",
    "Language": "Kieli",
    "Theme": "Teema",
    "Notifications": "Ilmoitukset",
    "Support": "Tuki",
    "Documentation": "Dokumentaatio",
    "Help": "Ohje",
    "Contact": "Yhteystiedot",
    "About": "Tietoja",
    "Version": "Versio",
    "Copyright": "Tekijänoikeus",
    "Powered by": "Powered by",
    "Welcome": "Tervetuloa",
    "Welcome back": "Tervetuloa takaisin",
    "Hello": "Hei",
    "Goodbye": "Näkemiin",
    "Thank you": "Kiitos",
    "Please wait...": "Odota...",
    "Processing...": "Käsitellään...",
    "Saving...": "Tallennetaan...",
    "Deleting...": "Poistetaan...",
    "Updating...": "Päivitetään...",
    "Connecting...": "Yhdistetään...",
    "Change IP": "Vaihda IP",
    "Server Unavailable": "Palvelin ei käytettävissä",
    "No Plans Purchased": "Ei ostettuja suunnitelmia",
    "You haven't purchased any plans yet. Explore our available plans and find the perfect one for your needs.": "Et ole ostanut vielä yhtään suunnitelmaa. Tutki saatavilla olevia suunnitelmia ja löydä sopivin tarpeisiisi.",
    "Manage your active plans and view billing information": "Hallinnoi aktiivisia suunnitelmiasi ja tarkastele laskutustietoja",
    "Choose from our wide selection di games for your server hosting": "Valitse laajasta pelivalikoimastamme palvelinhostaukseen",
    "Game Hosting": "Pelipalvelin",
    "Not available at the moment": "Ei saatavilla tällä hetkellä",
    "Custom hosting for any game": "Mukautettu hostaus mille tahansa pelille",
    "If you don't find the game you're looking for, you can request cusam hosting by joining our Discord.": "Jos et löydä etsimääsi peliä, voit pyytää mukautettua hostausta liittymällä Discordiimme.",
    "Ready a Play?": "Valmis pelaamaan?",
    "Let's create your free server in just a few steps.": "Luodaan ilmainen palvelimesi muutamassa vaiheessa.",
    "We offer a variety of server types, versions, and locations to suit your needs.": "Tarjoamme useita palvelintyyppejä, versioita ja sijainteja tarpeidesi mukaisesti.",
    "Starter": "Aloittelija",
    "Standard": "Vakio",
    "Power": "Tehokas",
    "Ultra": "Ultra",
    "Unlimited Players": "Rajoittamaton määrä pelaajia",
    "Unlimited Mods/Plugins": "Rajoittamaton määrä modeja/liitännäisiä",
    "Important: Read This First!": "Tärkeää: Lue tämä ensin!",
    "Before creating your server, please read our guide to understand how the renewal system works. This will help you keep your server online 24/7!": "Ennen palvelimen luomista, lue oppaamme ymmärtääksesi uusintajärjestelmän toiminnan. Tämä auttaa pitämään palvelimesi päällä 24/7!",
    "Read the Guide Now": "Lue opas nyt",
    "Read Guide First!": "Lue opas ensin!",
    "📖 Read Guide First!": "📖 Lue opas ensin!",
    "How Server Renewals Work": "Miten palvelimien uusiminen toimii",
    "Everything you need to know!": "Kaikki mitä sinun tarvitsee tietää!",
    "Daily Renewal System": "Päivittäinen uusintajärjestelmä",
    "The renew system ensures your server stays online based on your activity and plan. Each plan requires a specific number of renewals every 24 hours. For example, if your plan needs 6 renewals per day, you'll need to renew it roughly every 4 hours to keep it running.": "Uusintajärjestelmä varmistaa, että palvelimesi pysyy online-tilassa toimintasi ja suunnitelmasi perusteella. Jokainen suunnitelma vaatii tietyn määrän uusintoja 24 tunnin aikana. Esimerkiksi, jos suunnitelmasi vaatii 6 uusintaa päivässä, sinun on uusittava se noin joka 4. tunti pitääksesi sen käynnissä.",
    "Cooldown Period": "Viiveaika",
    "There is a waiting time between each renewal, which also depends on your plan. You can only renew again after this cooldown period has passed": "Jokaisen uusinnan välillä on odotusaika, joka riippuu myös suunnitelmastasi. Voit uusia uudelleen vasta, kun tämä viiveaika on kulunut",
    "Daily Reset": "Päivittäinen nollaus",
    "The daily renewal count resets at midnight (00:00 UTC), so each day you start with a fresh limit.": "Päivittäinen uusintamäärä nollautuu keskiyöllä (00:00 UTC), joten joka päivä aloitat uudella rajalla.",
    "Keep It Running 24/7": "Pidä se käynnissä 24/7",
    "As long as you keep renewing on time, your server will stay online 24/7.": "Niin kauan kuin uusit ajoissa, palvelimesi pysyy online-tilassa 24/7.",
    "What If I Miss a Renewal?": "Mitä jos unohdan uusinnan?",
    "If you miss a renewal, the server will be suspended, but you still have 15 days to renew it before it gets permanently deleted.": "Jos unohdat uusinnan, palvelin keskeytetään, mutta sinulla on vielä 15 päivää aikaa uusia se ennen kuin se poistetaan pysyvästi.",
    "In no other case will your server be reset or deleted.": "Missään muussa tapauksessa palvelintasi nollata tai poisteta.",
    "Got it": "Selvä",
    "What kind of server would you like to create?": "Millaisen palvelimen haluat luoda?",
    "How it Works": "Miten se toimii",
    "Which version do you want to use?": "Mitä versiota haluat käyttää?",
    "Renew every": "Uusi joka",
    "Max renewals/day": "Maksimi uusintoja/päivä",
    "Where do you want your server to be hosted?": "Mistä haluat palvelimesi isännöitävän?",
    "Great location for EU customers.": "Erinomainen sijainti EU-asiakkaille.",
    "Great location for US customers.": "Erinomainen sijainti USA-asiakkaille.",
    "Disclaimer": "Vastuuvapauslauseke",
    "By creating a server, you agree to the Minecraft EULA. Please ensure you understand and accept the terms before proceeding.": "Luomalla palvelimen hyväksyt Minecraft EULA:n. Varmista, että ymmärrät ja hyväksyt ehdot ennen jatkamista.",
    "Please ensure you understand and accept the terms before proceeding.": "Varmista, että ymmärrät ja hyväksyt ehdot ennen jatkamista.",
    "By creating a server, you agree to the ": "Luomalla palvelimen hyväksyt ",
    "You can't create more free servers. Maximum is 1 per user.": "Et voi luoda enempää ilmaisia palvelimia. Maksimi on 1 per käyttäjä.",
    "Get Server ID": "Hae palvelintunnus",
    "Wiki e Guides": "Wiki & oppaat",
    "Share your logs": "Jaa lokisi",
    "Analyze logs with AI": "Analysoi lokit tekoälyllä",
    "Players Online": "Pelaajia online",
    "DISK": "LEVY",
    "RAM": "Keskusmuisti",
    "Recycle Bin": "Roskakori",
    "Create directory": "Luo hakemisto",
    "Upload folder": "Lataa kansio palvelimelle",
    "Need help managing files? Check out our ": "Tarvitsetko apua tiedostojen hallinnassa? Tutustu ",
    "Navigation & Actions": "Navigointi & toiminnot",
    "Files & Folders": "Tiedostot & kansiot",
    "Search & Filters": "Haku & suodattimet",
    "Find plugins by name or functionality": "Etsi liitännäisiä nimen tai toiminnallisuuden perusteella",
    "No available plugins a install.": "Ei asennettavia liitännäisiä saatavilla.",
    "Versions": "Versiot",
    "Options": "Valinnat",
    "Find specific server settings quickly by searching their names": "Löydä tiettyjä palvelinasetuksia nopeasti hakemalla niiden nimillä",
    "Basic server settings that every Minecraft server owner should configure": "Peruspalvelinasetukset, jotka jokaisen Minecraft-palvelimen omistajan tulisi määrittää",
    "Configura your Minecraft world generation and behavior": "Määritä Minecraft-maailmasi generointi ja käyttäytyminen",
    "Control who can join your server and security features": "Hallitse, kuka voi liittyä palvelimeesi ja turvaominaisuuksia",
    "Advanced server configuration for experienced users": "Edistynyt palvelinkonfiguraatio kokeneille käyttäjille",
    "Additional server configuration options": "Lisäpalvelinkonfiguraatiovaihtoehdot",
    "Player Management": "Pelaajien hallinta",
    "Player Manager": "Pelaajien hallinta",
    "No Player Selected": "Ei pelaajaa valittuna",
    "Select a player from the list to view details and manage their data": "Valitse pelaaja listasta nähdäksesi tiedot ja hallinnoimaan heidän tietojaan",
    "Some modpacks may require additional installation steps that the server cannot perform automatically.": "Jotkut modipaketit saattavat vaatia lisäasennusvaiheita, joita palvelin ei voi suorittaa automaattisesti.",
    "Always check the modpack documentation and make sure it is compatible with your server setup.": "Tarkista aina modipaketin dokumentaatio ja varmista, että se on yhteensopiva palvelinasetustesi kanssa.",
    "Need help with modpack installation? Check our comprehensive guide:": "Tarvitsetko apua modipaketin asennuksessa? Tutustu kattavaan oppaaseemme:",
    "Browse Modpacks": "Selaa modipaketteja",
    "Got it!": "Selvä!",
    "Search Modpacks": "Hae modipaketteja",
    "Databases Unavailable": "Tietokannat eivät käytettävissä",
    "Database creation is not available for this server.": "Tietokantojen luonti ei ole saatavilla tälle palvelimelle.",
    "Create New Schedule": "Luo uusi aikataulu",
    "Create automated tasks that run on a schedule to manage your server.": "Luo automatisoituja tehtäviä, jotka suoritetaan aikataulun mukaisesti palvelimesi hallintaan.",
    "No Schedules Found": "Aikatauluja ei löytynyt",
    "Create your first schedule to automate server tasks and maintenance.": "Luo ensimmäinen aikataulusi automatisoidaksesi palvelintehtäviä ja ylläpitoa.",
    "Create Schedule": "Luo aikataulu",
    "Create new schedule": "Luo uusi aikataulu",
    "A human readable identifier for this schedule.": "Ihmisluettava tunniste tälle aikataululle.",
    "The schedule system supports the use of Cronjob syntax when defining when tasks should begin running. Use the fields above to specify when these tasks should begin running.": "Aikataulujärjestelmä tukee Cronjob-syntaksin käyttöä määriteltäessä, milloin tehtävien pitäisi alkaa suorittua. Käytä yllä olevia kenttiä määrittääksesi, milloin nämä tehtävät alkavat suorittua.",
    "Show Cheatsheet": "Näytä pikaopas",
    "Show the cron cheatsheet for some examples.": "Näytä cron-pikaopas joitakin esimerkkejä varten.",
    "Only When Server Is Online": "Vain kun palvelin on online-tilassa",
    "Only execute this schedule when the server is in a running state.": "Suorita tämä aikataulu vain, kun palvelin on käynnissä.",
    "Schedule Enabled": "Aikataulu käytössä",
    "This schedule will be executed automatically if enabled.": "Tämä aikataulu suoritetaan automaattisesti, jos se on käytössä.",
    "Add New User": "Lisää uusi käyttäjä",
    "Grant other users access to your server with customizable permissions.": "Myönnä muille käyttäjille pääsy palvelimeesi mukautettavien käyttöoikeuksien kautta.",
    "No Users Found": "Käyttäjiä ei löytynyt",
    "Add users to your server to collaborate and share access with custom permissions.": "Lisää käyttäjiä palvelimeesi tehdäksesi yhteistyötä ja jakaa pääsy mukautettujen käyttöoikeuksien kautta.",
    "Empty": "Tyhjä",
    "Backups Unavailable": "Varmuuskopiot eivät käytettävissä",
    "Backups cannot be created for this server because the backup limit is set to 0.": "Varmuuskopioita ei voi luoda tälle palvelimelle, koska varmuuskopioraja on asetettu 0:aan.",
    "Create New Subdomain": "Luo uusi alidomain",
    "Choose a unique name for your subdomain": "Valitse uniikki nimi alidomainillesi",
    "Create custom subdomains to provide easy access to your server. Instead of using IP addresses, your users can connect through friendly URLs.": "Luo mukautettuja alidomaineja helpon pääsyn tarjoamiseksi palvelimeesi. IP-osoitteiden sijaan käyttäjät voivat muodostaa yhteyden ystävällisten URL-osoitteiden kautta.",
    "Create your first subdomain to get started with custom domain routing": "Luo ensimmäinen alidomainisi aloittaaksesi mukautetun domainreitityksen",
    "No Subdomains Found": "Alidomaineja ei löytynyt",
    "are automatically routed to your server": "reititetään automaattisesti palvelimellesi",
    "Example subdomain:": "Esimerkki alidomainista:",
    "This is the command that will be executed when your server starts.": "Tämä on komento, joka suoritetaan palvelimesi käynnistyessä.",
    "This is an advanced feature allowing you a select a Docker image to use when running this server instance.": "Tämä on edistynyt ominaisuus, jonka avulla voit valita Docker-kuvan, jota käytetään tätä palvelininstanssia suoritettaessa.",
    "Configura environment variables that control your server's behavior and settings.": "Määritä ympäristömuuttujat, jotka hallitsevat palvelimesi käyttäytymistä ja asetuksia.",
    "Staffs can request an access a your server. If you accept it, staff can manage it. But you can deny it anytime.": "Henkilökunta voi pyytää pääsyä palvelimeesi. Jos hyväksyt sen, henkilökunta voi hallita sitä. Mutta voit evätä sen milloin tahansa.",
    "There are no access requests for this server.": "Tälle palvelimelle ei ole pääsypyyntöjä.",
    "SFTP Connection Details": "SFTP-yhteyden yksityiskohdat",
    "Your SFTP password is the same as the password you use to access this panel.": "SFTP-salasana on sama kuin salasana, jota käytät tämän paneelin käyttämiseen.",
    "Server identification and technical details": "Palvelimen tunnistus ja tekniset tiedot",
    "Change Server Details": "Muuta palvelimen tietoja",
    "Update your server name and description": "Päivitä palvelimesi nimi ja kuvaus",
    "Reset your server to its original state": "Palauta palvelimesi alkuperäiseen tilaan",
    "Reinstalling your server will stop it, and then re-run the installation script that initially set it up.": "Palvelimesi uudelleenasennus pysäyttää sen ja suorittaa uudelleen alkuperäisen asennuskomentosarjan.",
    "Some files may be deleted or modified during this process, please back up your data before continuing.": "Jotkut tiedostot saattavat poistua tai muuttua tämän prosessin aikana, varmuuskopioi tietosi ennen jatkamista.",
    "Activity Timeline": "Toiminnan aikajana",
    "No activity logs available for this server.": "Toimintalokeja ei ole saatavilla tälle palvelimelle.",
    "Server actions and events will appear here when they occur.": "Palvelintoiminnot ja tapahtumat näkyvät täällä, kun ne tapahtuvat.",
    "Server Suspended": "Palvelin keskeytetty",
    "Your free server has expired.": "Ilmainen palvelimesi on vanhentunut.",
    "Free Server Expired": "Ilmainen palvelin vanhentunut",
    "Expired on:": "Vanhentunut:",
    "Renew your free server to continue playing!": "Uusi ilmainen palvelimesi jatkaaksesi pelaamista!",
    "Keep Your Server Alive!": "Pidä palvelimesi hengissä!",
    "Watch a quick ad to keep your awesome server running!": "Katso nopea mainos pitääksesi mahtavan palvelimesi käynnissä!",
    "All times shown in": "Kaikki ajat näytetään",
    "Get": "Hanki",
    "more hours": "tuntia lisää",
    "for FREE!": "ILMAISEKSI!",
    "Just watch a short ad and your server stays online!": "Katso vain lyhyt mainos ja palvelimesi pysyy online-tilassa!",
    "Your Renewal Stats": "Uusintatilastosi",
    "Renewals Today:": "Uusintoja tänään:",
    "Next renewal ready:": "Seuraava uusinta valmis:",
    "Renew my awesone server": "Uusi mahtava palvelimeni",
    "Server Always in Queue?": "Palvelin aina jonossa?",
    "Move your server to a faster location!": "Siirrä palvelimesi nopeampaan sijaintiin!",
    "Try a Different Server Node!": "Kokeile eri palvelinsolmua!",
    "Experiencing long queue times? Transfer your server to a different location for better performance!": "Koket pitkiä jonotusajoita? Siirrä palvelimesi toiseen sijaintiin paremman suorituskyvyn saamiseksi!",
    "Important": "Tärkeää",
    "Make a backup first!": "Tee ensin varmuuskopio!",
    "Quick Transfer": "Pikasiirto",
    "Choose Location": "Valitse sijainti",
    "RAM Boost Power!": "Keskusmuistitehoboosti!",
    "Get extra RAM by watching a quick ad!": "Hanki ylimääräistä keskusmuistia katsomalla nopea mainos!",
    "Current RAM": "Nykyinen keskusmuisti",
    "Available Boosts": "Käytettävissä olevat boostit",
    "boost available": "boosti saatavilla",
    "Choose from": "Valitse",
    "configuration": "konfiguraatio",
    "Select Boost": "Valitse boosti",
    "Upgrade Your Server!": "Päivitä palvelimesi!",
    "Get more RAM, CPU power, and storage space!": "Hanki enemmän keskusmuistia, suoritintehoa ja tallennustilaa!",
    "Customize Your Server Resources": "Mukauta palvelimesi resursseja",
    "Change your server's configuration to get more RAM, CPU, disk space, and other cool features!": "Muuta palvelimesi konfiguraatiota saadaksesi enemmän keskusmuistia, suoritinta, levytilaa ja muita hienoja ominaisuuksia!",
    "Note": "Huomio",
    "You'll need to restart your server after upgrading!": "Sinun on käynnistettävä palvelimesi uudelleen päivityksen jälkeen!",
    "Upgrade Server!": "Päivitä palvelin!",
    "Never Miss a Renewal!": "Älä koskaan missaa uusintaa!",
    "Get notified when your server needs attention!": "Saat ilmoituksen, kun palvelimesi tarvitsee huomiota!",
    "Smart Notification System": "Älykäs ilmoitusjärjestelmä",
    "Get browser notifications and in-game messages when your server is about to expire!": "Saat selainilmoituksia ja pelin sisäisiä viestejä, kun palvelimesi on vanhentumassa!",
    "Never forget": "Älä koskaan unohda",
    "Keep your server running 24/7!": "Pidä palvelimesi käynnissä 24/7!",
    "Setup Notifications": "Määritä ilmoitukset",
    "Danger Zone": "Vaaravyöhyke",
    "Permanently delete your server and all data": "Poista palvelimesi ja kaikki tiedot pysyvästi",
    "This action cannot be undone!": "Tätä toimintoa ei voi kumota!",
    "Once deleted, your server and all its files will be gone forever. Make sure you have backups!": "Kun palvelin on poistettu, palvelimesi ja kaikki sen tiedostot ovat poissa ikuisesti. Varmista, että sinulla on varmuuskopiot!",
    "Delete Server Forever": "Poista palvelin ikuisesti",
    "This server has been suspended.": "Tämä palvelin on keskeytetty.",
    "You need a renew it to continue using it.": "Sinun on uusittava se jatkaaksesi sen käyttöä.",
    "Page Not Found - Access Denied": "Sivua ei löytynyt - Pääsy evätty"
}