{
    "Dashboard": "Instrumentpanel",
    "Staff": "Personal",
    "Manager": "Chef",
    "Admin": "Administratör",
    "Account Settings": "Kontoinställningar",
    "Sign Out": "Logga ut",
    "Home": "Hem",
    "Account": "Konto",
    "Security": "Säkerhet",
    "API Credentials": "API-Referenser",
    "SSH Keys": "SSH-nycklar",
    "API": "API",
    "SSH": "SSH",
    "Activity": "Aktivitet",
    "Logout": "Logga ut",
    "Portal": "Portal",
    "Premium Server": "Premiumserver",
    "Free Server": "Gratis server",
    "Tutorials": "Handledningar",
    "Discord": "Discord",
    "Server": "Server",
    "Console": "Konsol",
    "Files": "Filer",
    "Showing your servers": "Visar dina servrar",
    "Showing others' servers": "Visar andras servrar",
    "You are a premium user! To redeem your customer role and access premium support, join our Discord and create a ticket.": "Du är en premiumanvändare! För att hämta din kundroll och få tillgång till premiumsupport, gå med i vår Discord och skapa en ticket.",
    "Create Free Server": "Skapa gratis server",
    "No servers found.": "Inga servrar hittades.",
    "It looks like you have no servers.": "Det verkar som att du inte har några servrar.",
    "All Rights Reserved.": "Alla rättigheter förbehållna.",
    "Terms of Service": "Användarvillkor",
    "Privacy Policy": "Integritetspolicy",
    "Create": "Skapa",
    "Save": "Spara",
    "Cancel": "Avbryt",
    "Delete": "Radera",
    "Edit": "Redigera",
    "Update": "Uppdatera",
    "Back": "Tillbaka",
    "Close": "Stäng",
    "Confirm": "Bekräfta",
    "Yes": "Ja",
    "No": "Nej",
    "Submit": "Skicka",
    "View Details": "Visa detaljer",
    "Search": "Sök",
    "Filter": "Filtrera",
    "Import": "Importera",
    "Export": "Exportera",
    "Download": "Ladda ner",
    "Upload": "Ladda upp",
    "Connect": "Anslut",
    "Disconnect": "Koppla från",
    "Copy": "Kopiera",
    "Refresh": "Uppdatera",
    "Apply": "Tillämpa",
    "Return to Login": "Återgå till inloggning",
    "Install": "Installera",
    "Uninstall": "Avinstallera",
    "Reinstall": "Ominstallera",
    "Configure": "Konfigurera",
    "View": "Visa",
    "Start": "Starta",
    "Stop": "Stoppa",
    "Restart": "Starta om",
    "Kill": "Döda",
    "Send": "Skicka",
    "Continue": "Fortsätt",
    "Next": "Nästa",
    "Previous": "Föregående",
    "Finish": "Slutför",
    "Reset": "Återställ",
    "Clear": "Rensa",
    "Select": "Välj",
    "Deselect": "Avmarkera",
    "Enable": "Aktivera",
    "Disable": "Inaktivera",
    "Active": "Aktiv",
    "Inactive": "Inaktiv",
    "Pending": "Väntande",
    "Completed": "Slutförd",
    "Failed": "Misslyckades",
    "Loading": "Laddar",
    "Loading...": "Laddar...",
    "Success": "Lyckades",
    "Error": "Fel",
    "Warning": "Varning",
    "Info": "Info",
    "Online": "Online",
    "Offline": "Offline",
    "Starting": "Startar",
    "Stopping": "Stoppar",
    "Running": "Körs",
    "Suspended": "Suspenderad",
    "Installing": "Installerar",
    "Restoring": "Återställer",
    "Transferring": "Överför",
    "Successfully saved.": "Sparades framgångsrikt.",
    "Successfully updated.": "Uppdaterades framgångsrikt.",
    "Successfully deleted.": "Raderades framgångsrikt.",
    "Successfully created.": "Skapades framgångsrikt.",
    "Are you sure you want to delete this?": "Är du säker på att du vill radera detta?",
    "This action cannot be undone.": "Denna åtgärd kan inte ångras.",
    "No results found.": "Inga resultat hittades.",
    "No servers found matching your search.": "Inga servrar hittades som matchar din sökning.",
    "Searching...": "Söker...",
    "Copied to clipboard": "Kopierat till urklipp",
    "Click to copy": "Klicka för att kopiera",
    "Click to copy allocation(s)": "Klicka för att kopiera tilldelning(ar)",
    "Something went wrong.": "Något gick fel.",
    "An error occurred.": "Ett fel uppstod.",
    "Please try again later.": "Vänligen försök igen senare.",
    "Access Denied": "Åtkomst nekad",
    "You do not have permission to access this page.": "Du har inte behörighet att komma åt denna sida.",
    "Page not found": "Sidan hittades inte",
    "The page you are looking for does not exist.": "Sidan du letar efter existerar inte.",
    "Name": "Namn",
    "Description": "Beskrivning",
    "Email": "E-post",
    "Password": "Lösenord",
    "Current Password": "Nuvarande lösenord",
    "New Password": "Nytt lösenord",
    "Confirm Password": "Bekräfta lösenord",
    "Confirm New Password": "Bekräfta nytt lösenord",
    "Username": "Användarnamn",
    "Type to search...": "Skriv för att söka...",
    "Search...": "Sök...",
    "Notes": "Anteckningar",
    "Reason": "Anledning",
    "Value": "Värde",
    "Key": "Nyckel",
    "Variable": "Variabel",
    "Port": "Port",
    "IP Address": "IP-adress",
    "Host": "Värd",
    "Database": "Databas",
    "Databases": "Databaser",
    "This field is required": "Detta fält är obligatoriskt",
    "Please enter a valid email address": "Vänligen ange en giltig e-postadress",
    "Passwords do not match": "Lösenorden matchar inte",
    "Password must be at least 8 characters": "Lösenordet måste vara minst 8 tecken långt",
    "Optional": "Valfritt",
    "Required": "Obligatoriskt",
    "File Manager": "Filhanterare",
    "Server Info": "Serverinfo",
    "Schedules": "Scheman",
    "Users": "Användare",
    "Backups": "Säkerhetskopior",
    "Network": "Nätverk",
    "Startup": "Uppstart",
    "Settings": "Inställningar",
    "Terminal": "Terminal",
    "Modpacks": "Modpaket",
    "Mods": "Modifikationer",
    "Properties": "Egenskaper",
    "World Manager": "Världshanterare",
    "Google Drive Backup": "Säkerhetskopiering till Google Drive",
    "Plugin manager": "Tilläggshanterare",
    "Minecraft Player Manager": "Minecraft Spelarhanterare",
    "Servers": "Servrar",
    "Server Name": "Servernamn",
    "Server Description": "Serverbeskrivning",
    "Server Status": "Serverstatus",
    "Server Information": "Serverinformation",
    "Server Settings": "Serverinställningar",
    "SFTP Details": "SFTP-detaljer",
    "Debug Information": "Felsökningsinformation",
    "Reinstall Server": "Ominstallera server",
    "Transfer Server": "Överför server",
    "Delete Server": "Radera server",
    "Memory": "Minne",
    "CPU": "CPU",
    "Disk": "Disk",
    "Disk Space": "Diskutrymme",
    "Current Resource Usage": "Nuvarande resursanvändning",
    "Allocated": "Tilldelat",
    "Used": "Använt",
    "Available": "Tillgängligt",
    "New File": "Ny fil",
    "New Folder": "Ny mapp",
    "Upload Files": "Ladda upp filer",
    "File Name": "Filnamn",
    "Folder Name": "Mappnamn",
    "Size": "Storlek",
    "Last Modified": "Senast ändrad",
    "Permissions": "Behörigheter",
    "Compress": "Komprimera",
    "Decompress": "Dekomprimera",
    "Archive": "Arkivera",
    "Extract": "Extrahera",
    "Rename": "Byt namn",
    "Move": "Flytta",
    "Mass Delete": "Massradera",
    "Schedule": "Schema",
    "New Schedule": "Nytt schema",
    "Schedule Name": "Schemanamn",
    "Enabled": "Aktiverad",
    "Disabled": "Inaktiverad",
    "Last Run": "Senast körde",
    "Next Run": "Nästa körning",
    "Tasks": "Uppgifter",
    "New Task": "Ny uppgift",
    "Task": "Uppgift",
    "Action": "Åtgärd",
    "Actions": "Åtgärder",
    "Payload": "Nyttolast",
    "Time Offset": "Tidsförskjutning",
    "Continue on Failure": "Fortsätt vid fel",
    "Backup": "Säkerhetskopia",
    "Create Backup": "Skapa säkerhetskopia",
    "Backup Name": "Säkerhetskopianamn",
    "Locked": "Låst",
    "Unlocked": "Olåst",
    "Checksum": "Kontrollsumma",
    "Restore": "Återställ",
    "Download Backup": "Ladda ner säkerhetskopia",
    "Delete Backup": "Radera säkerhetskopia",
    "Lock Backup": "Lås säkerhetskopia",
    "Unlock Backup": "Lås upp säkerhetskopia",
    "User": "Användare",
    "Email Address": "E-postadress",
    "Subusers": "Underanvändare",
    "New User": "Ny användare",
    "Invite User": "Bjud in användare",
    "Grant Permissions": "Bevilja behörigheter",
    "Revoke Permissions": "Återkalla behörigheter",
    "Select All": "Markera alla",
    "Deselect All": "Avmarkera alla",
    "Allocations": "Tilldelningar",
    "Primary": "Primär",
    "Make Primary": "Gör till primär",
    "Alias": "Alias",
    "Assign Additional Ports": "Tilldela ytterligare portar",
    "Startup Command": "Uppstartskommando",
    "Startup Variables": "Uppstartvariabler",
    "Docker Image": "Dockeravbildning",
    "Default Value": "Standardvärde",
    "Billing": "Fakturering",
    "Balance": "Saldo",
    "Cart": "Kundvagn",
    "My Plans": "Mina planer",
    "Manage": "Hantera",
    "Plugin": "Tillägg",
    "Account Balance": "Kontosaldo",
    "PayPal": "PayPal",
    "Stripe": "Stripe",
    "Gift Card": "Presentkort",
    "Billing Information": "Faktureringsinformation",
    "Please enter the amount you would like to add": "Vänligen ange beloppet du vill lägga till",
    "Amount": "Belopp",
    "Card Holder Name": "Korthållarens namn",
    "Card Number": "Kortnummer",
    "Expiration Date": "Utgångsdatum",
    "CVV": "CVV",
    "Pay Now": "Betala nu",
    "Address": "Adress",
    "First Name": "Förnamn",
    "Last Name": "Efternamn",
    "City": "Stad",
    "Country": "Land",
    "State": "Stat",
    "Province": "Provins",
    "Postal Code": "Postnummer",
    "ZIP Code": "Postnummer",
    "Phone": "Telefon",
    "Phone Number": "Telefonnummer",
    "Update Billing Information": "Uppdatera faktureringsinformation",
    "Edit Account": "Redigera konto",
    "Account API": "Konto-API",
    "Admin Area": "Administrationsområde",
    "Dark Mode": "Mörkt läge",
    "Light Mode": "Ljust läge",
    "Gift Card Code": "Presentkortskod",
    "Redeem": "Lös in",
    "Balance:": "Saldo:",
    "Current Balance:": "Nuvarande saldo:",
    "Checkout": "Gå till kassan",
    "Game": "Spel",
    "Plan": "Plan",
    "Price": "Pris",
    "Billed": "Faktureras",
    "Cart is empty.": "Kundvagnen är tom.",
    "Place Order": "Lägg beställning",
    "Plan Name": "Plannamn",
    "Total": "Totalt",
    "Subtotal": "Delsumma",
    "Discount": "Rabatt",
    "Total Order: ": "Totalbeställning: ",
    "After clicking \"Confirm Order\", your order will be placed and the amount will be reduced from your current balance.": "Efter att du klickat på \"Bekräfta beställning\" kommer din beställning att läggas och beloppet kommer att dras från ditt nuvarande saldo.",
    "Discount Code": "Rabattkod",
    "Apply Discount": "Tillämpa rabatt",
    "Remove from Cart": "Ta bort från kundvagn",
    "Date": "Datum",
    "View Plans": "Visa planer",
    "View Invoices": "Visa fakturor",
    "Extend": "Förläng",
    "days for": "dagar för",
    "Deleted": "Raderad",
    "Pay": "Betala",
    "Are you sure?": "Är du säker?",
    "Remove": "Ta bort",
    "Plans": "Planer",
    "Add to Cart": "Lägg till i kundvagn",
    "Monthly": "Månatligt",
    "Yearly": "Årligen",
    "Year": "År",
    "Quarterly": "Kvartalsvis",
    "Weekly": "Veckovis",
    "Daily": "Dagligen",
    "One Time": "Engångs",
    "Unlimited": "Obegränsat",
    "Days": "dagar",
    "Hours": "timmar",
    "Minutes": "minuter",
    "CPU:": "CPU:",
    "RAM:": "RAM:",
    "Disk:": "Disk:",
    "Storage:": "Lagring:",
    "Backup(s)": "Säkerhetskopia(or)",
    "Database(s)": "Databas(er)",
    "Extra Ports": "Extra portar",
    "Slots": "Platser",
    "Players": "Spelare",
    "Invoice": "Faktura",
    "Invoices": "Fakturor",
    "Invoice Date:": "Fakturadatum:",
    "Due Date:": "Förfallodatum:",
    "Invoice Date": "Fakturadatum",
    "Due Date": "Förfallodatum",
    "Price:": "Pris:",
    "Status": "Status",
    "Paid": "Betalat",
    "Unpaid": "Obetalt",
    "Overdue": "Förfallen",
    "Cancelled": "Avbruten",
    "Refunded": "Återbetald",
    "Renew Plan": "Förnya plan",
    "View Invoice": "Visa faktura",
    "Request Cancellation": "Begär avbokning",
    "Renew": "Förnya",
    "Plan added to cart": "Plan lades till i kundvagnen",
    "Your server has been created successfully, go to My Plans for more information.": "Din server har skapats, gå till Mina planer för mer information.",
    "Payment successful!": "Betalning lyckades!",
    "Order placed successfully!": "Beställning placerad!",
    "Balance added successfully!": "Saldo tillagt!",
    "Sorry. You must first remove all plans that belong to this game.": "Du måste först ta bort alla planer som tillhör detta spel.",
    "Sorry. You have reached a limit. You can only purchase the following amount: ": "Du har nått en gräns. Du kan bara köpa följande antal: ",
    "An error occurred while creating a new server.": "Ett fel uppstod när en ny server skulle skapas.",
    "There is not enough balance in your account to make this purchase.": "Det finns inte tillräckligt med saldo på ditt konto för att göra detta köp.",
    "Plan has been removed from your cart.": "Planen har tagits bort från din kundvagn.",
    "There are no plans for this game.": "Det finns inga planer för detta spel.",
    "Invalid discount code.": "Ogiltig rabattkod.",
    "Discount code expired.": "Rabattkoden har gått ut.",
    "Payment failed.": "Betalning misslyckades.",
    "Insufficient funds.": "Otillräckliga medel.",
    "Today": "Idag",
    "Yesterday": "Igår",
    "Tomorrow": "Imorgon",
    "Now": "Nu",
    "Never": "Aldrig",
    "Just now": "Just nu",
    "a minute ago": "en minut sedan",
    "minutes ago": "minuter sedan",
    "an hour ago": "en timme sedan",
    "hours ago": "timmar sedan",
    "a day ago": "en dag sedan",
    "days ago": "dagar sedan",
    "a week ago": "en vecka sedan",
    "weeks ago": "veckor sedan",
    "a month ago": "en månad sedan",
    "months ago": "månader sedan",
    "a year ago": "ett år sedan",
    "years ago": "år sedan",
    "Page": "Sida",
    "of": "av",
    "Showing": "Visar",
    "to": "till",
    "entries": "poster",
    "results": "resultat",
    "First": "Första",
    "Last": "Sista",
    "Language": "Språk",
    "Theme": "Tema",
    "Notifications": "Aviseringar",
    "Support": "Support",
    "Documentation": "Dokumentation",
    "Help": "Hjälp",
    "Contact": "Kontakt",
    "About": "Om",
    "Version": "Version",
    "Copyright": "Upphovsrätt",
    "Powered by": "Drivs av",
    "Welcome": "Välkommen",
    "Welcome back": "Välkommen tillbaka",
    "Hello": "Hej",
    "Goodbye": "Hej då",
    "Thank you": "Tack",
    "Please wait...": "Vänligen vänta...",
    "Processing...": "Bearbetar...",
    "Saving...": "Sparar...",
    "Deleting...": "Raderar...",
    "Updating...": "Uppdaterar...",
    "Connecting...": "Ansluter...",
    "Change IP": "Ändra IP",
    "Server Unavailable": "Servern otillgänglig",
    "No Plans Purchased": "Inga planer köpta",
    "You haven't purchased any plans yet. Explore our available plans and find the perfect one for your needs.": "Du har inte köpt några planer ännu. Utforska våra tillgängliga planer och hitta den perfekta för dina behov.",
    "Manage your active plans and view billing information": "Hantera dina aktiva planer och visa faktureringsinformation",
    "Choose from our wide selection di games for your server hosting": "Välj från vårt stora utbud av spel för din serverhosting",
    "Game Hosting": "Spelhosting",
    "Not available at the moment": "Inte tillgängligt just nu",
    "Custom hosting for any game": "Anpassad hosting för vilket spel som helst",
    "If you don't find the game you're looking for, you can request cusam hosting by joining our Discord.": "Om du inte hittar spelet du letar efter, kan du begära anpassad hosting genom att gå med i vår Discord.",
    "Ready a Play?": "Redo att spela?",
    "Let's create your free server in just a few steps.": "Låt oss skapa din gratis server på bara några steg.",
    "We offer a variety of server types, versions, and locations to suit your needs.": "Vi erbjuder en mängd olika servertyper, versioner och platser för att passa dina behov.",
    "Starter": "Starter",
    "Standard": "Standard",
    "Power": "Power",
    "Ultra": "Ultra",
    "Unlimited Players": "Obegränsade spelare",
    "Unlimited Mods/Plugins": "Obegränsade modifikationer/tillägg",
    "Important: Read This First!": "Viktigt: Läs detta först!",
    "Before creating your server, please read our guide to understand how the renewal system works. This will help you keep your server online 24/7!": "Innan du skapar din server, vänligen läs vår guide för att förstå hur förnyelse systemet fungerar. Detta hjälper dig att hålla din server online dygnet runt!",
    "Read the Guide Now": "Läs guiden nu",
    "Read Guide First!": "Läs guiden först!",
    "📖 Read Guide First!": "📖 Läs guiden först!",
    "How Server Renewals Work": "Hur serverförnyelser fungerar",
    "Everything you need to know!": "Allt du behöver veta!",
    "Daily Renewal System": "Dagligt förnyelsesystem",
    "The renew system ensures your server stays online based on your activity and plan. Each plan requires a specific number of renewals every 24 hours. For example, if your plan needs 6 renewals per day, you'll need to renew it roughly every 4 hours to keep it running.": "Förnyelsesystemet säkerställer att din server hålls online baserat på din aktivitet och plan. Varje plan kräver ett specifikt antal förnyelser varje 24:e timme. Till exempel, om din plan kräver 6 förnyelser per dag, måste du förnya den ungefär var 4:e timme för att hålla den igång.",
    "Cooldown Period": "Nedkylningstid",
    "There is a waiting time between each renewal, which also depends on your plan. You can only renew again after this cooldown period has passed": "Det finns en väntetid mellan varje förnyelse, vilket också beror på din plan. Du kan bara förnya igen efter att denna nedkylningstid har passerat",
    "Daily Reset": "Daglig återställning",
    "The daily renewal count resets at midnight (00:00 UTC), so each day you start with a fresh limit.": "Antalet dagliga förnyelser återställs vid midnatt (00:00 UTC), så varje dag startar du med en frisk gräns.",
    "Keep It Running 24/7": "Håll det igång dygnet runt",
    "As long as you keep renewing on time, your server will stay online 24/7.": "Så länge du förnyar i tid, kommer din server att hållas online dygnet runt.",
    "What If I Miss a Renewal?": "Vad händer om jag missar en förnyelse?",
    "If you miss a renewal, the server will be suspended, but you still have 15 days to renew it before it gets permanently deleted.": "Om du missar en förnyelse kommer servern att suspenderas, men du har fortfarande 15 dagar på dig att förnya den innan den raderas permanent.",
    "In no other case will your server be reset or deleted.": "I inget annat fall kommer din server att återställas eller raderas.",
    "Got it": "Jag förstår",
    "What kind of server would you like to create?": "Vilken sorts server vill du skapa?",
    "How it Works": "Hur det fungerar",
    "Which version do you want to use?": "Vilken version vill du använda?",
    "Renew every": "Förnya varje",
    "Max renewals/day": "Max förnyelser/dag",
    "Where do you want your server to be hosted?": "Var vill du att din server ska vara hostad?",
    "Great location for EU customers.": "Bra plats för EU-kunder.",
    "Great location for US customers.": "Bra plats för US-kunder.",
    "Disclaimer": "Ansvarsbegränsning",
    "By creating a server, you agree to the Minecraft EULA. Please ensure you understand and accept the terms before proceeding.": "Genom att skapa en server godkänner du Minecrafts EULA. Vänligen säkerställ att du förstår och accepterar villkoren innan du fortsätter.",
    "Please ensure you understand and accept the terms before proceeding.": "Vänligen säkerställ att du förstår och accepterar villkoren innan du fortsätter.",
    "By creating a server, you agree to the ": "Genom att skapa en server godkänner du ",
    "You can't create more free servers. Maximum is 1 per user.": "Du kan inte skapa fler gratis servrar. Max är 1 per användare.",
    "Get Server ID": "Få server-ID",
    "Wiki e Guides": "Wiki & Guider",
    "Share your logs": "Dela dina loggar",
    "Analyze logs with AI": "Analysera loggar med AI",
    "Players Online": "Spelare online",
    "DISK": "DISK",
    "RAM": "RAM",
    "Recycle Bin": "Papperskorg",
    "Create directory": "Skapa katalog",
    "Upload folder": "Ladda upp mapp",
    "Need help managing files? Check out our ": "Behöver du hjälp med att hantera filer? Kolla in vår ",
    "Navigation & Actions": "Navigation & Åtgärder",
    "Files & Folders": "Filer & Mappar",
    "Search & Filters": "Sök & Filter",
    "Find plugins by name or functionality": "Hitta tillägg efter namn eller funktionalitet",
    "No available plugins a install.": "Inga tillgängliga tillägg att installera.",
    "Versions": "Versioner",
    "Options": "Alternativ",
    "Find specific server settings quickly by searching their names": "Hitta specifika serverinställningar snabbt genom att söka efter deras namn",
    "Basic server settings that every Minecraft server owner should configure": "Grundläggande serverinställningar som varje Minecraft-serverägare bör konfigurera",
    "Configura your Minecraft world generation and behavior": "Konfigurera din Minecraft-världsgenerering och beteende",
    "Control who can join your server and security features": "Kontrollera vem som kan ansluta till din server och säkerhetsfunktioner",
    "Advanced server configuration for experienced users": "Avancerad serverkonfiguration för erfarna användare",
    "Additional server configuration options": "Ytterligare serverkonfigurationsalternativ",
    "Player Management": "Spelarhantering",
    "Player Manager": "Spelarhanterare",
    "No Player Selected": "Ingen spelare vald",
    "Select a player from the list to view details and manage their data": "Välj en spelare från listan för att visa detaljer och hantera deras data",
    "Some modpacks may require additional installation steps that the server cannot perform automatically.": "Vissa modpaket kan kräva ytterligare installationssteg som servern inte kan utföra automatiskt.",
    "Always check the modpack documentation and make sure it is compatible with your server setup.": "Kontrollera alltid modpakets dokumentation och säkerställ att det är kompatibelt med din serverkonfiguration.",
    "Need help with modpack installation? Check our comprehensive guide:": "Behöver du hjälp med modpaketinstallation? Kolla in vår omfattande guide:",
    "Browse Modpacks": "Bläddra bland modpaket",
    "Got it!": "Jag förstår!",
    "Search Modpacks": "Sök modpaket",
    "Databases Unavailable": "Databaser otillgängliga",
    "Database creation is not available for this server.": "Databasskapande är inte tillgängligt för denna server.",
    "Create New Schedule": "Skapa nytt schema",
    "Create automated tasks that run on a schedule to manage your server.": "Skapa automatiserade uppgifter som körs enligt ett schema för att hantera din server.",
    "No Schedules Found": "Inga scheman hittades",
    "Create your first schedule to automate server tasks and maintenance.": "Skapa ditt första schema för att automatisera serveruppgifter och underhåll.",
    "Create Schedule": "Skapa schema",
    "Create new schedule": "Skapa nytt schema",
    "A human readable identifier for this schedule.": "En läsbar identifierare för detta schema.",
    "The schedule system supports the use of Cronjob syntax when defining when tasks should begin running. Use the fields above to specify when these tasks should begin running.": "Schematsystemet stöder användning av Cronjob-syntax när man definierar när uppgifter ska börja köras. Använd fälten ovan för att specificera när dessa uppgifter ska börja köras.",
    "Show Cheatsheet": "Visa fusklapp",
    "Show the cron cheatsheet for some examples.": "Visa cron-fusklappen för några exempel.",
    "Only When Server Is Online": "Endast när servern är online",
    "Only execute this schedule when the server is in a running state.": "Kör endast detta schema när servern är i ett körande tillstånd.",
    "Schedule Enabled": "Schema aktiverat",
    "This schedule will be executed automatically if enabled.": "Detta schema kommer att köras automatiskt om det är aktiverat.",
    "Add New User": "Lägg till ny användare",
    "Grant other users access to your server with customizable permissions.": "Ge andra användare tillgång till din server med anpassningsbara behörigheter.",
    "No Users Found": "Inga användare hittades",
    "Add users to your server to collaborate and share access with custom permissions.": "Lägg till användare till din server för att samarbeta och dela åtkomst med anpassade behörigheter.",
    "Empty": "Tom",
    "Backups Unavailable": "Säkerhetskopior otillgängliga",
    "Backups cannot be created for this server because the backup limit is set to 0.": "Säkerhetskopior kan inte skapas för denna server eftersom säkerhetskopieringsgränsen är satt till 0.",
    "Create New Subdomain": "Skapa nytt underdomän",
    "Choose a unique name for your subdomain": "Välj ett unikt namn för din underdomän",
    "Create custom subdomains to provide easy access to your server. Instead of using IP addresses, your users can connect through friendly URLs.": "Skapa anpassade underdomäner för att tillhandahålla enkel åtkomst till din server. Istället för att använda IP-adresser kan dina användare ansluta genom vänliga URL:er.",
    "Create your first subdomain to get started with custom domain routing": "Skapa din första underdomän för att komma igång med anpassad domänroutning",
    "No Subdomains Found": "Inga underdomäner hittades",
    "are automatically routed to your server": "dirigeras automatiskt till din server",
    "Example subdomain:": "Exempel på underdomän:",
    "This is the command that will be executed when your server starts.": "Detta är kommandot som kommer att köras när din server startar.",
    "This is an advanced feature allowing you a select a Docker image to use when running this server instance.": "Detta är en avancerad funktion som tillåter dig att välja en Dockeravbildning att använda när denna serverinstans körs.",
    "Configura environment variables that control your server's behavior and settings.": "Konfigurera miljövariabler som styr din servers beteende och inställningar.",
    "Staffs can request an access a your server. If you accept it, staff can manage it. But you can deny it anytime.": "Personal kan begära tillgång till din server. Om du accepterar det kan personal hantera den. Men du kan neka det när som helst.",
    "There are no access requests for this server.": "Det finns inga åtkomstförfrågningar för denna server.",
    "SFTP Connection Details": "SFTP-anslutningsdetaljer",
    "Your SFTP password is the same as the password you use to access this panel.": "Ditt SFTP-lösenord är samma som det lösenord du använder för att komma åt denna panel.",
    "Server identification and technical details": "Serveridentifiering och tekniska detaljer",
    "Change Server Details": "Ändra serverdetaljer",
    "Update your server name and description": "Uppdatera ditt servernamn och beskrivning",
    "Reset your server to its original state": "Återställ din server till dess ursprungliga tillstånd",
    "Reinstalling your server will stop it, and then re-run the installation script that initially set it up.": "Ominstallation av din server stoppar den och kör sedan installationskriptet som ursprungligen satte upp den.",
    "Some files may be deleted or modified during this process, please back up your data before continuing.": "Vissa filer kan raderas eller ändras under denna process, vänligen säkerhetskopiera dina data innan du fortsätter.",
    "Activity Timeline": "Aktivitetslinje",
    "No activity logs available for this server.": "Inga aktivitetsloggar tillgängliga för denna server.",
    "Server actions and events will appear here when they occur.": "Serveråtgärder och händelser kommer att visas här när de inträffar.",
    "Server Suspended": "Server Suspenderad",
    "Your free server has expired.": "Din gratis server har gått ut.",
    "Free Server Expired": "Gratis server gått ut",
    "Expired on:": "Gick ut den:",
    "Renew your free server to continue playing!": "Förnya din gratis server för att fortsätta spela!",
    "Keep Your Server Alive!": "Håll din server vid liv!",
    "Watch a quick ad to keep your awesome server running!": "Titta på en snabb reklam för att hålla din fantastiska server igång!",
    "All times shown in": "Alla tider visas i",
    "Get": "Få",
    "more hours": "fler timmar",
    "for FREE!": "GRATIS!",
    "Just watch a short ad and your server stays online!": "Titta bara på en kort reklam och din server hålls online!",
    "Your Renewal Stats": "Dina förnyelsedata",
    "Renewals Today:": "Förnyelser idag:",
    "Next renewal ready:": "Nästa förnyelse redo:",
    "Renew my awesone server": "Förnya min fantastiska server",
    "Server Always in Queue?": "Server alltid i kö?",
    "Move your server to a faster location!": "Flytta din server till en snabbare plats!",
    "Try a Different Server Node!": "Prova en annan servernod!",
    "Experiencing long queue times? Transfer your server to a different location for better performance!": "Upplever du långa kötid? Överför din server till en annan plats för bättre prestanda!",
    "Important": "Viktigt",
    "Make a backup first!": "Gör en säkerhetskopia först!",
    "Quick Transfer": "Snabb Överföring",
    "Choose Location": "Välj plats",
    "RAM Boost Power!": "RAM-boostkraft!",
    "Get extra RAM by watching a quick ad!": "Få extra RAM genom att titta på en snabb reklam!",
    "Current RAM": "Nuvarande RAM",
    "Available Boosts": "Tillgängliga boostar",
    "boost available": "boost tillgänglig",
    "Choose from": "Välj från",
    "configuration": "konfiguration",
    "Select Boost": "Välj boost",
    "Upgrade Your Server!": "Uppgradera din server!",
    "Get more RAM, CPU power, and storage space!": "Få mer RAM, CPU-kraft och lagringsutrymme!",
    "Customize Your Server Resources": "Anpassa dina serverresurser",
    "Change your server's configuration to get more RAM, CPU, disk space, and other cool features!": "Ändra din servers konfiguration för att få mer RAM, CPU, diskutrymme och andra coola funktioner!",
    "Note": "Obs",
    "You'll need to restart your server after upgrading!": "Du måste starta om din server efter uppgradering!",
    "Upgrade Server!": "Uppgradera server!",
    "Never Miss a Renewal!": "Missa aldrig en förnyelse!",
    "Get notified when your server needs attention!": "Få aviseringar när din server behöver uppmärksamhet!",
    "Smart Notification System": "Smart aviseringsystem",
    "Get browser notifications and in-game messages when your server is about to expire!": "Få webbläsaraviseringar och meddelanden i spelet när din server håller på att gå ut!",
    "Never forget": "Glöm aldrig",
    "Keep your server running 24/7!": "Håll din server igång dygnet runt!",
    "Setup Notifications": "Ställ in aviseringar",
    "Danger Zone": "Farozon",
    "Permanently delete your server and all data": "Radera din server och alla data permanent",
    "This action cannot be undone!": "Denna åtgärd kan inte ångras!",
    "Once deleted, your server and all its files will be gone forever. Make sure you have backups!": "När den är raderad kommer din server och alla dess filer att vara borta för alltid. Säkerställ att du har säkerhetskopior!",
    "Delete Server Forever": "Radera server för alltid",
    "This server has been suspended.": "Denna server har suspenderats.",
    "You need a renew it to continue using it.": "Du måste förnya den för att fortsätta använda den.",
    "Page Not Found - Access Denied": "Sidan hittades inte - Åtkomst nekad"
}